SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF OBJECT_ID('[dbo].[t_TypesOfDebt]','U') IS NOT NULL
	DROP TABLE [dbo].[t_TypesOfDebt]
GO

CREATE TABLE [dbo].[t_TypesOfDebt](
	[ID] [int] NOT NULL,
	[ТипДолга] [varchar](64) NOT NULL,
 CONSTRAINT [PK_t_TOD_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO [dbo].[t_TypesOfDebt] VALUES (1, 'Аванс')
INSERT INTO [dbo].[t_TypesOfDebt] VALUES (2, 'Просрочено')
INSERT INTO [dbo].[t_TypesOfDebt] VALUES (3, 'Не просрочено')

SET ANSI_PADDING OFF
GO